[window settings]
## Size only required if fullscreen is not active
Size = "800x600"
Fullscreen = "True"
## Transparency goes from 1 to 0
Transparency = ""

[colors]
Background      = "#011627"
Foreground      = "#bdc1c6"
Bold 	          = "#eeeeee"
Cursor 	       = "#9ca1aa"
Cursor_Text     = "#080808"
Selection 	    = "#b2ceee"
Selection_Text  = "#080808"
Black   	       = "#1d3b53"
Red     	       = "#fc514e"
Green   	       = "#a1cd5e"
Yellow  	       = "#e3d18a"
Blue            = "#82aaff"
Purple  	       = "#c792ea"
Cyan    	       = "#7fdbca"
White           = "#a1aab8"
Black_Bright    = "#7c8f8f"
Red_Bright      = "#ff5874"
Green_Bright    = "#21c7a8"
Yellow_Bright   = "#ecc48d"
Blue_Bright     = "#82aaff"
Purple_Bright   = "#ae81ff"
Cyan_Bright     = "#7fdbca"
White_Bright    = "#d6deeb"

[font]
## Default font is JetBrainsMono and is installed by default
##file = ""
size = 14
