[window]
## Dimensions only required if fullscreen is not active
Dimensions = "800x600"
Fullscreen = "True"

## Frame sets it so you have a window frame or window decorations if you use windows
# Importand if not fullscreen, as no "alt drag" function is implemented
# If fullscreen frame will not be used
Frame = "False"

# If frame = True then this will appear
Title = ""

## Opacity goes from 1 to 0
Opacity = "0.85"

[font]
## If left empty will use JetBrainsMono
Font_family = "" #Use only name if font is installed in the os or use path if not
Size = 14

[colors]
# Frame color if frame is true, hex or transparent 
Frame_color     = "Transparent"
 
Background      = "#011627"
Foreground      = "#bdc1c6"
Bold 	          = "#eeeeee"
Cursor 	       = "#9ca1aa"
Cursor_Text     = "#080808"
Selection 	    = "#b2ceee"
Selection_Text  = "#080808"
Black   	       = "#1d3b53"
Red     	       = "#fc514e"
Green   	       = "#a1cd5e"
Yellow  	       = "#e3d18a"
Blue            = "#82aaff"
Purple  	       = "#c792ea"
Cyan    	       = "#7fdbca"
White           = "#a1aab8"
Black_Bright    = "#7c8f8f"
Red_Bright      = "#ff5874"
Green_Bright    = "#21c7a8"
Yellow_Bright   = "#ecc48d"
Blue_Bright     = "#82aaff"
Purple_Bright   = "#ae81ff"
Cyan_Bright     = "#7fdbca"
White_Bright    = "#d6deeb"
